### ISSUE TITLE
Add a way to get an option's value?

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [altrisi/CaffeineConfig#1]
My mod, VanillaDisable, adds many gamerules. It uses CaffeineConfig. Of course, CaffeineConfig toggles the mixins for the gamerules. However, the gamerules still exist, just don't do anything. It would be useful to be able to get the value of the option in order to be able to put the gamerule definitions in an if statement, therefore if the mixins are disabled, I just disable the gamerule.

**Comment by altrisi** [comment]
Doesn't `CaffeineConfig#getEffectiveOptionForMixin` do exactly what you're looking for? (it gives you an `Option` that you can check if it's enabled/overridden/whatever)

You should be able to get the CaffeineConfig object out when you create it in the `createConfig` method, or call other code directly from there (given option values are parsed when `build` is called).

**Comment by DragonEggBedrockBreaking** [comment]
It seems to be working now, thanks!
